package chapter1.patternStart;

import edu.duke.URLResource;
import chapter1.readInFile.ReadInFile;

import java.util.List;

/**
 * Created by callie on 8/12/16.
 */
public class PatternStartTester {
    public static void main(String[] args) {
        String pattern = "GCCCTTGGC";
//        URLResource file = new URLResource("http://bioinformaticsalgorithms.com/data/realdatasets/Replication/Vibrio_cholerae.txt");
//        ReadInFile rif = new ReadInFile(file);
//        String genome = rif.readInURL();
        String genome = "ACGCCCTTGTACACGGTACGCCCTTGGCCCTTGTCGCCCTTGGCCCTTGTTACCGCCCTTGGAGGCCCTTGAGGGCCCTTGCGCCCTTGTCGGCCCTTGTGCCCTTGCGTCGCCCTTGGCCCTTGGCCCTTGCCGCCCTTGCTCTACATGCCCTTGGCCCTTGGCCCTTGGAAGGGGCCCTTGTGCCCTTGCTTGCCCTTGTGGTGCCCTTGAGCCCTTGCGTGGTCGCCCTTGGCCCTTGAGTCGCCCTTGCAGCCCTTGGTCGCCCTTGGCCCTTGAACGCCCTTGTAGCCCTTGGCCCTTGCGCCCGCCCTTGCGCCCTTGTTGTGCCCTTGGCCCTTGCTCCAGAGGCCCTTGCGGGCCCTTGAGCCCTTGTCTGGTGCCCTTGTTACGGCCCTTGACAAAGAGCCCTTGTGCCCTTGTCTAAGCCCTTGCTGCCCTTGTGTGCCCTTGCCCGCCCTTGTGCCCTTGCGGCCCTTGCGCAGGGCCCTTGGCCCTTGGCAAATGCCCTTGATACCTCGTGTACAGCCCTTGTATGCGCCCTTGTGCCCTTGTACAAAAGCCCTTGGCCCTTGAGCCCTTGCCTGCCCTTGCCCGCCCTTGGCCCTTGGCCCTTGAGCCCTTGGCCCTTGGGCCCTTGGCCCTTGGCCCTTGCCGCCCTTGATAAGCCCTTGAACGCCCTTGATAGCCCTTGGCCCTTGGCCCTTGGCCCTTGACCCAGCAGGCCCTTGGCCCTTGGGGTCAGCCCTTGGCCCTTGGCCCTTGGCAAGCCCTTGACAAGTCGCCCTTGTGCCCTTGGCCCTTGATGACTGGCCCTTGAAGATTAGCCCTTGTCGCCCTAAACGTCGCCCTTGGAGCCCTTGAGCCCTTGTGCCCTTGACAGCCCTTGGGCCCTTGTCTGCCCTTGCGCCCTTGCACGCCCTTGACTGGCCCTTGCTGGGCCCTTGGCCCTTGGTGCCCTTG";
        PatternStart ps = new PatternStart(pattern,genome);
        List<Integer> startPos = ps.findPatternStart();
        for (Integer i : startPos) {
            System.out.print(i+" ");
        }
    }
}
